Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/OutputSafety:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true

AllCops:
  Exclude:
    - 'app/controllers/sb_admin_docs_controller.rb'
    - 'app/views/sb_admin_docs/*.html.haml'
    - 'app/views/layouts/sb_admin_docs.html.haml'
    - 'app/views/layouts/sb_admin_shared/*.html.haml'
    - 'app/helpers/active_link_to_helper.rb'
    - 'app/helpers/template_nav_helper.rb'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
require: rubocop-rails
