version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      # Bundle install dependencies
      - run: bundle install
      # Database setup
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rspec spec
