version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb
  rubocop: hanachin/rubocop@0.0.6

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0-node-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
        # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-{{ checksum "Gemfile.lock" }}
            - rails-demo-
      # Bundle install dependencies
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3
      - run: sudo apt install -y postgresql-client || true
      # Store bundle cache
      - save_cache:
          key: rails-demo-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Database setup
      - run: yarn install --check-files
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
          when: always
      - store_test_results:
          path: ~/rspec

workflows:
  heroku_deploy:
    jobs:
      - rubocop/rubocop
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master
